version: "3.9"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./conf/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    depends_on:
      - pgadmin
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"
    command: postgres -c max_connections=100
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "--dbname=rinha",
          "--username=postgres"
        ]
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "rafaelpadovezi@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"

  api1: &api1
    build: .
    hostname: api1
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
  api2: 
    <<: *api1
    hostname: api2
    ports:
      - "8080:8080"
  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
