version: "3.9"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./conf/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./conf/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    depends_on:
      - pgadmin
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.4"
    #       memory: "200MB"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "--dbname=rinha",
          "--username=postgres"
        ]
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "rafaelpadovezi@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"

  api1: &api1
    build: .
    hostname: api1
    depends_on:
      pgbouncer:
        condition: service_started
    environment:
      - DB_HOST=db
      - USE_STATIC_FILE_HANDLER_FROM_WSGI=TRUE
      - DATABASE_URL=host=db dbname=rinha user=postgres password=postgres
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.40"
  api2: 
    <<: *api1
    hostname: api2
    ports:
      - "8081:8080"
  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.16"
          memory: "20MB"

  pgbouncer:
    image: edoburu/pgbouncer
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_NAME=rinha
      - POOL_MODE=session
      - ADMIN_USERS=postgres,dbuser
      - AUTH_TYPE=scram-sha-256
      - DEFAULT_POOL_SIZE=50
    depends_on:
      db:
        condition: service_healthy
    # volumes:
    #   - ./conf/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
    #   - ./conf/userlist.txt:/etc/pgbouncer/userlist.txt:ro
    ports:
      - "6432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '100MB'